version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/demo
      - /demo/sample_app/tmp
      - /demo/hello_app/tmp
      - /demo/toy_app/tmp
    tty: true
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
